Created struct for Team and Player
phnilsson/CloudNativeComputingGroupB pull request #12
Opened 2023-04-12 16:31 UTC by yaElevDorota

If Team tables empty - creating one

2023-04-12 17:47 UTC, phnilsson requested changes

2023-04-12 17:47 UTC, phnilsson commented on data/entities.go
> +type Player struct {
Player ska även ha fältet "birthYear".

2023-04-12 20:46 UTC, yaElevDorota commented on data/entities.go
> +type Player struct {
added BirthYear

2023-04-13 05:51 UTC, phnilsson approved these changes

2023-04-13 16:31 UTC, merged